INSERT INTO dim_finalite VALUES (1, 0, 1, 'Non renseignée', 1);
INSERT INTO dim_finalite VALUES (2, 0, 2, 'Refusé', 2);
INSERT INTO dim_finalite VALUES (3, 0, 3, 'Accepté', 3);
INSERT INTO dim_finalite VALUES (7, 0, 6, 'En cours', 6);
INSERT INTO dim_finalite VALUES (4, 0, 4, 'Corbeille', 5);
INSERT INTO dim_finalite VALUES (5, 0, 5, 'Transformé', 6);
INSERT INTO dim_jour_paiement VALUES (1, 0, '5', 1);
INSERT INTO dim_jour_paiement VALUES (2, 0, '10', 2);
INSERT INTO dim_jour_paiement VALUES (3, 0, '15', 4);
INSERT INTO dim_lien_familial VALUES (1, 0, 'Adhérent');
INSERT INTO dim_lien_familial VALUES (2, 0, 'Conjoint');
INSERT INTO dim_lien_familial VALUES (3, 0, 'Enfant');
INSERT INTO dim_motif_devis VALUES (1, 0, 'Standard', false, 1);
INSERT INTO dim_motif_devis VALUES (2, 0, 'Parrainage', false, 2);
INSERT INTO dim_moyen_paiement VALUES (1, 0, 'Carte Bancaire', 1);
INSERT INTO dim_moyen_paiement VALUES (2, 0, 'Chèque', 2);
INSERT INTO dim_moyen_paiement VALUES (3, 0, 'Prélèvement', 3);
INSERT INTO dim_moyen_paiement VALUES (4, 0, 'Espèces', 4);
INSERT INTO dim_moyen_paiement VALUES (5, 0, 'Mandat', 5);
INSERT INTO dim_moyen_paiement VALUES (6, 0, 'Virement', 6);
INSERT INTO dim_moyen_paiement VALUES (7, 0, 'Virement encaissement', 7);
INSERT INTO dim_periodicite_paiement VALUES (1, 0, 'Mensuelle', 1);
INSERT INTO dim_periodicite_paiement VALUES (2, 0, 'Trimestrielle', 2);
INSERT INTO dim_periodicite_paiement VALUES (3, 0, 'Semestrielle', 3);
INSERT INTO dim_periodicite_paiement VALUES (4, 0, 'Annuelle', 4);
INSERT INTO dim_source_ligne_devis VALUES (1, 1, 'Commerciale');
INSERT INTO dim_source_ligne_devis VALUES (3, 3, 'Demande dossier');
INSERT INTO dim_source_ligne_devis VALUES (5, 5, 'Consultation tarifs');
INSERT INTO dim_source_ligne_devis VALUES (4, 4, 'Adhesion en ligne');
