INSERT INTO dim_finalite VALUES (1, 0, 1, 'Unspecified', 1);
INSERT INTO dim_finalite VALUES (2, 0, 2, 'Refused', 2);
INSERT INTO dim_finalite VALUES (3, 0, 3, 'Accepted', 3);
INSERT INTO dim_finalite VALUES (7, 0, 6, 'In progress', 6);
INSERT INTO dim_finalite VALUES (4, 0, 4, 'Trash', 5);
INSERT INTO dim_finalite VALUES (5, 0, 5, 'Transformed', 6);
INSERT INTO dim_jour_paiement VALUES (1, 0, '5', 1);
INSERT INTO dim_jour_paiement VALUES (2, 0, '10', 2);
INSERT INTO dim_jour_paiement VALUES (3, 0, '15', 4);
INSERT INTO dim_lien_familial VALUES (1, 0, 'Member');
INSERT INTO dim_lien_familial VALUES (2, 0, 'Husband / Wife');
INSERT INTO dim_lien_familial VALUES (3, 0, 'Child');
INSERT INTO dim_motif_devis VALUES (1, 0, 'Standard', false, 1);
INSERT INTO dim_motif_devis VALUES (2, 0, 'Sponsorship', false, 2);
INSERT INTO dim_moyen_paiement VALUES (1, 0, 'Credit Card', 1);
INSERT INTO dim_moyen_paiement VALUES (2, 0, 'Check', 2);
INSERT INTO dim_moyen_paiement VALUES (3, 0, 'Levy', 3);
INSERT INTO dim_moyen_paiement VALUES (4, 0, 'Cash', 4);
INSERT INTO dim_moyen_paiement VALUES (5, 0, 'Warrant', 5);
INSERT INTO dim_moyen_paiement VALUES (6, 0, 'Transfer', 6);
INSERT INTO dim_moyen_paiement VALUES (7, 0, 'Transfer receipt', 7);
INSERT INTO dim_periodicite_paiement VALUES (1, 0, 'Monthly', 1);
INSERT INTO dim_periodicite_paiement VALUES (2, 0, 'Quarterly', 2);
INSERT INTO dim_periodicite_paiement VALUES (3, 0, 'Semester', 3);
INSERT INTO dim_periodicite_paiement VALUES (4, 0, 'Yearly', 4);
INSERT INTO dim_source_ligne_devis VALUES (1, 1, 'Commercial');
INSERT INTO dim_source_ligne_devis VALUES (3, 3, 'Quote request');
INSERT INTO dim_source_ligne_devis VALUES (5, 5, 'Rates Consultation');
INSERT INTO dim_source_ligne_devis VALUES (4, 4, 'Online membership');
